SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOT_SPEED = 500
PLAYER_SHOT_COOLDOWN = 0.3

SHOT_RADIUS = 2
PARTICLE_RADIUS = 2

POWER_UP_RADIUS = 30
POWER_UP_SPAWN_RATE = 7
POWER_UP_VELOCITY = 100